clc;
clear;

%% 参数初始化
RP_data = Module_Lib();
Configuration_Lib = { ...
    [1 2 1], ...
    [1 2 3 2 5 1 2], ...
    [1 2 3 1 2 3 1], ...
    [1 1 1 2 1 2 2], ...
    [2 2 2 2 2 2 2], ...
    [] ...
    };
module = [ ...
    Configuration_Lib{1}, ...
    Configuration_Lib{2}, ...
    ];
install = [ ...
    ones(1,length(Configuration_Lib{1})), ...
    ones(1,length(Configuration_Lib{2})) ...
    ];
align = [ ...
    [0 0 0] ...
    zeros(1,length(Configuration_Lib{2})) ...
    ];
sequence = [ ...
    0  1  2, ...
    0  4  5  6 7 8 9, ...
    ];
LP = LP_generate(module, install, align, sequence, RP_data);
SV = SV_generate(LP);

%% 正运动学
% q0 = rand(LP.num_joint,1)  * pi * 2;
% SV = Trans_aa_pos(LP, SV, q0);

%% 目标设置
Goal = Goal_init(LP,SV);
Goal.change = [0 1 0];
Goal.POS{2}  = [1;1;5];


%% 逆运动学求解
[LP, SV, flag] = check_kinematics_0318(LP, SV, Goal);

%% 绘构型图可视化(验证)
PlotSV(LP,SV);

%% 可操作度计算

w = calc_Manipulability_0318(LP, SV);


% q0 = rand(LP.num_joint,1)  * pi * 0;
% SV = aa_pos(LP, SV, q0);
% PlotSV(LP,SV);
% % SV = Trans_aa_pos(LP, SV, q0);
% norm([0;0;3.5]-[0;-0.433;-0.25])
